caravan/config/routes.rb
Rails.application.routes.draw do
	resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

caravan/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

caravan/app/models/blog.rb
class Blog < ApplicationRecord
end

caravan/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

caravan/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def show
    @blog = Blog.find(params[:id])
  end

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    blog = Blog.new(blog_params)
    blog.save
    redirect_to blogs_path
  end


  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)
    redirect_to blog_path(blog)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to blogs_path   
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :category, :body)
  end
    

end

caravan/app/helpers/application_helper.rb
module ApplicationHelper
end

caravan/app/helpers/blogs_helper.rb
module BlogsHelper
end

caravan/app/views/blogs/edit.html.erb
<h1>編集画面</h1>
<!-- form_for部分 -->
<%= form_for(@blog) do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>カテゴリー</h4>
  <%= f.text_field :category %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '保存' %>

<% end %>

caravan/app/views/blogs/index.html.erb
<header>
    <section id="header_container">
      <h1 id="logo"><a href="/">CARAVAN</a></h1>
      <div id="social">
        <i class="fa fa-facebook-square" aria-hidden="true"></i>
        <i class="fa fa-twitter-square" aria-hidden="true"></i>
        <i class="fa fa-instagram" aria-hidden="true"></i>      
      </div>
    </section>
  </header>
  <nav>
    <ul>
      <li>Home</li>
      <li>About</li>
      <li>Topic</li>
    </ul>
  </nav>
  <main>
    <div id="main_visual">
      <div class="black_mask">
        <p class="mv_text">The world is a book<br>and those who do not travel<br>read only one page.</p>
        <p class="mv_name">St. Augustine</p>
      </div>
    </div>
    <article id="main_container" class="clearfix">
      <section id="recent_blogs">
        <h2>Recent Blogs</h2>
        <div class="blog_item_box">
          <% @blogs.each do |blog| %>
            <div class="blog_item clearfix">
              <div class="blog_image"></div>
              <section class="blog_text">
                <h3><%= link_to blog.title, blog_path(blog) %></h3>
                <p><%= blog.created_at %></p>
                <span class="category"><%= blog.category %></span>
              </section>
            </div>
          <% end %>
        </div>
        <div id="pagination">
          <p><<</p>
          <p><</p>
          <p>1</p>
          <p>2</p>
          <p>3</p>
          <p>></p>
          <p>>></p>
        </div>
      </section>
      <section id="sidebar">
        <section id="popular">
          <h2>Popular</h2>
          <div class="sidebar_contents">
            <p>To solve old problems,<br>study new species</p>
            <p>Why Earth may someday<br>look like Mars</p>
            <p>What will humans look<br>like in 100 years?</p>
            <p>How to grow a forest<br>in your backyard</p>
            <p>How humans could evolve<br>to survive in space</p>
          </div>
        </section>
        <section id="instagram">
          <h2>Instagram</h2>
          <div class="sidebar_contents clearfix">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        </section>
        <section id="categories">
          <h2>categories</h2>
          <div class="sidebar_contents">
            <p>Technology(15)</p>
            <p>Business(23)</p>
            <p>Entertainment(12)</p>
            <p>Nature(32)</p>
            <p>Education(9)</p>
            <p>Adventure(23)</p>
            <p>Communication(14)</p>
          </div>
        </section>
      </section>
    </article>
  </main> 
  <footer>
    <p>© All rights recerved by Infratop.Inc.</p>
  </footer>

caravan/app/views/blogs/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for @blog do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>カテゴリー</h4>
  <%= f.text_field :category %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>

  <% end %>

caravan/app/views/blogs/show.html.erb
<header>
    <section id="header_container">
      <h1 id="logo"><a href="/">CARAVAN</a></h1>
      <div id="social">
        <i class="fa fa-facebook-square" aria-hidden="true"></i>
        <i class="fa fa-twitter-square" aria-hidden="true"></i>
        <i class="fa fa-instagram" aria-hidden="true"></i>      
      </div>
    </section>
  </header>
  <nav>
    <ul>
      <li><a href="index.html">Home</a></li>
      <li>About</li>
      <li>Topic</li>
      <li>Map</li>
      <li>Contact</li>
      <li>Link</li>
    </ul>
  </nav>
  <main>
    <div id="main_visual">
      <div class="black_mask">
        <p class="mv_text">The world is a book<br>and those who do not travel<br>read only one page.</p>
        <p class="mv_name">St. Augustine</p>
      </div>
    </div>
    <article id="main_container" class="clearfix">
      <section id="recent_blogs">
        <h2>Blog</h2>
        <section class="blog_item_box">
          <h3>
            <!-- 変更部分 -->
            <%= @blog.title %>
          </h3>
          <div>
            <p class="category">
              <!-- 変更部分 -->
              <%= @blog.category %>
            </p>
            <p>June 19, 2017</p>
          </div>
          <img src="https://wals.s3.amazonaws.com/uploads/wals2_content_img/CaravanImg/img/forest.jpg" class="single_image" alt="forest">
          <p class="single_text">
            <!-- テキスト部分を削除して以下のコードに書き換える -->
            <%= @blog.body %>    
          </p>
          
          <!-- 追加部分 -->
          <%= link_to "編集", edit_blog_path(@blog) %>
          <!-- 追加部分 -->
          <%= link_to "削除", blog_path(@blog), method: :delete %>
          
          <div class="author_case clearfix">
            <div class="author_image"></div>
            <div class="author_text">
              <p class="author_name">By JOHN SMITH / Photographer</p>
              <p>His black and white landscapes, often captured at times<br>of the day and night when the light is fleeting, or in poor<br>weather conditions, such as rain, fog, or snow, are<br>reminiscent of the calm in a storm all with an ethereal<br>quality. </p>
            </div>
          </div>
        </section>
      </section>
      <section id="sidebar">
        <section id="popular">
          <h2>Popular</h2>
          <div class="sidebar_contents">
            <p>To solve old problems,<br>study new species</p>
            <p>Why Earth may someday<br>look like Mars</p>
            <p>What will humans look<br>like in 100 years?</p>
            <p>How to grow a forest<br>in your backyard</p>
            <p>How humans could evolve<br>to survive in space</p>
          </div>
        </section>
        <section id="instagram">
          <h2>Instagram</h2>
          <div class="sidebar_contents clearfix">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        </section>
        <section id="categories">
          <h2>categories</h2>
          <div class="sidebar_contents">
            <p>Technology(15)</p>
            <p>Business(23)</p>
            <p>Entertainment(12)</p>
            <p>Nature(32)</p>
            <p>Education(9)</p>
            <p>Adventure(23)</p>
            <p>Communication(14)</p>
          </div>
        </section>
      </section>
    </article>
  </main>
  <footer>
    <p>© All rights recerved by Infratop.Inc.</p>
  </footer>

caravan/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CARAVAN</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>